/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'category',
      label: 'Smart Contract Docs',
      items: ['contracts/contracts',
        {
          Lab: [
            'contracts/lab/LegendsLaboratory',
            'contracts/lab/TicketMachine',
            'contracts/lab/LaboratoryGovernor',
            'contracts/lab/Admin Overrides'
          ],
          Legend: [
            'contracts/legend/LegendsNFT',
            'contracts/legend/ILegendMetadata',
          ],
          Marketplace: [
            'contracts/marketplace/LegendsMarketplace',
            {
              Escrow: [
                'contracts/marketplace/escrow/LegendsMarketClerk',
                'contracts/marketplace/escrow/LegendsEscrow',
              ], listings: [
                'contracts/marketplace/listings/LegendSale',
                'contracts/marketplace/listings/LegendAuction',
                'contracts/marketplace/listings/ILegendListing',
              ],
            }],
          Matching: [
            'contracts/matching/LegendsMatchingBoard', {
              Match: [
                'contracts/matching/match/LegendMatching',
                'contracts/matching/match/ILegendMatch',
              ],
            }
          ],
          Rejuvenation: [
            'contracts/rejuvenation/LegendRejuvenation',
            'contracts/rejuvenation/IRejuvenationPod',
          ],
          Token: [
            'contracts/token/LegendToken',
          ],
        }],
    },
  ],

};

module.exports = sidebars;
